package cn.hdu.learn.miaosha.dal.model;

import java.util.Date;

public class MiaoshaUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_user.id
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_user.name
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_user.age
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    private Long age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_user.create_time
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_user.update_time
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_user.id
     *
     * @return the value of miaosha_user.id
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_user.id
     *
     * @param id the value for miaosha_user.id
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_user.name
     *
     * @return the value of miaosha_user.name
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_user.name
     *
     * @param name the value for miaosha_user.name
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_user.age
     *
     * @return the value of miaosha_user.age
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public Long getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_user.age
     *
     * @param age the value for miaosha_user.age
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public void setAge(Long age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_user.create_time
     *
     * @return the value of miaosha_user.create_time
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_user.create_time
     *
     * @param createTime the value for miaosha_user.create_time
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_user.update_time
     *
     * @return the value of miaosha_user.update_time
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_user.update_time
     *
     * @param updateTime the value for miaosha_user.update_time
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}