package cn.hdu.learn.miaosha.internal.api.ro;

import lombok.Data;

/**
 * 描述：
 *
 * @author guaner
 * @date 2019/4/7
 */
@Data
public class MiaoshaUserRO {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_user.id
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_user.name
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_user.age
     *
     * @mbggenerated Sun Apr 07 11:27:24 CST 2019
     */
    private Long age;

}
